name: Build and Sign APK & AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and sign AAB
        uses: vga-software/sign-android-app@v1.1
        with:
          app-name: "pk-ai"
          app-version: "1.0.0"
          signing-key: ${{ secrets.SIGNING_KEY }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          key-store-password: ${{ secrets.KEY_STORE_PASSWORD }}
          build-type: "aab"

      - name: Build and sign APK
        uses: vga-software/sign-android-app@v1.1
        with:
          app-name: "pk-ai"
          app-version: "1.0.0"
          signing-key: ${{ secrets.SIGNING_KEY }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          key-store-password: ${{ secrets.KEY_STORE_PASSWORD }}
          build-type: "apk"
